// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHNT-6lEtnOBxYRkLT_R6iH1Oq33crcK0',
    appId: '1:938895149011:web:7df4c544a454cfdce3d126',
    messagingSenderId: '938895149011',
    projectId: 'ai-field-assistant-7f9dc',
    authDomain: 'ai-field-assistant-7f9dc.firebaseapp.com',
    storageBucket: 'ai-field-assistant-7f9dc.firebasestorage.app',
    measurementId: 'G-G1J6VFW82E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHjN4OdLCM3PVlFAfjS83V06OgR0Y-BQ',
    appId: '1:938895149011:android:f96ca5fdf1255bb3e3d126',
    messagingSenderId: '938895149011',
    projectId: 'ai-field-assistant-7f9dc',
    storageBucket: 'ai-field-assistant-7f9dc.firebasestorage.app',
  );
}
